name: Build and Push (GHCR)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tags
        id: meta
        run: |
          DATE=$(date +%Y%m%d)
          OWNER="${{ github.repository_owner }}"
          IMAGE="ghcr.io/${OWNER}/lin-aba"
          echo "TAGS=${IMAGE}:latest,${IMAGE}:${DATE},${IMAGE}:${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Containerfile
          push: true
          tags: ${{ steps.meta.outputs.TAGS }}
